services:
  postgres:
    image: postgres:18
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pa55w0rd!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports: 
      - 6379:6379

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "8081:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - kafka_data:/var/lib/kafka/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=adminpwd
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL","curl -s -f -u elastic:adminpwd http://localhost:9200/_cluster/health | grep -q 'status'"]
      interval: 5s
      timeout: 5s
      retries: 10

  elastic-setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elastic-setup
    depends_on:
      elasticsearch:
        condition: service_healthy
    command:
      - bash
      - -c
      - |
        echo "Configuring password for kibana_system..."
        until curl -s -f -X POST -u "elastic:adminpwd" -H "Content-Type: application/json" http://elasticsearch:9200/_security/user/kibana_system/_password -d '{"password":"adminpwd"}'; do 
          echo "Waiting for Elasticsearch to be ready for password changing"
          sleep 2
        done
        echo "Password for kibana_system successfully configured!"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=adminpwd
      - XPACK_FLEET_AGENTS_TLS_CHECK_DISABLED=true
    depends_on: 
      elastic-setup:
        condition: service_completed_successfully

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.12.2
    container_name: apm-server
    ports:
      - "8200:8200"
    command: >
      apm-server -e
      -E apm-server.rum.enabled=true
      -E setup.kibana.host=kibana:5601
      -E setup.kibana.username=elastic
      -E setup.kibana.password=adminpwd
      -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
      -E output.elasticsearch.username=elastic
      -E output.elasticsearch.password=adminpwd
    depends_on:
      kibana:
        condition: service_started

  tasks-tracker-service:
    build:
      context: .
      dockerfile: Services/TasksTrackerService/Dockerfile
    hostname: tasks-tracker-service
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "5006:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=TasksTracker;Username=postgres;Password=pa55w0rd!"
      RabbitMq__Host: "rabbitmq"
      RabbitMq__Username: "guest"
      RabbitMq__Password: "guest"
      ASPNETCORE_URLS: "http://+:80"

  history-service:
    build:
      context: .
      dockerfile: Services/History/Dockerfile
    hostname: history-service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_healthy
      tasks-tracker-service:
        condition: service_started
    ports:
      - "5004:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=History;Username=postgres;Password=pa55w0rd!"
      RabbitMq__Host: "rabbitmq"
      RabbitMq__Username: "guest"
      RabbitMq__Password: "guest"

  notification-service:
    build:
      context: .
      dockerfile: Services/Notification/Dockerfile
    hostname: notification-service
    depends_on:
      tasks-tracker-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "5005:80"
    environment:
      RabbitMq__Host: "rabbitmq"
      RabbitMq__Username: "guest"
      RabbitMq__Password: "guest"
      ASPNETCORE_URLS: "http://+:80"

volumes:
  elasticdata:
  kafka_data:
    driver: local