<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="DataSeeding\FemalePatronymics.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="DataSeeding\MalePatronymics.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.10" />
    <PackageReference Include="QuestPDF" Version="2026.2.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Shared\Shared.csproj" />
    <ProjectReference Include="..\EmployeesTasksTracker.TasksTrackerService.Application\EmployeesTasksTracker.TasksTrackerService.Application.csproj" />
    <ProjectReference Include="..\EmployeesTasksTracker.TasksTrackerService.Core\EmployeesTasksTracker.TasksTrackerService.Core.csproj" />
  </ItemGroup>

</Project>
