name: CI

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}
        
      - name: Restore dependencies
        run: dotnet restore EmployeesTasksTracker.sln

      - name: Build
        run: dotnet build EmployeesTasksTracker.sln --configuration $BUILD_CONFIGURATION Release --no-restore

  unit-tests:

    runs-on: ubuntu-latest

    needs: build

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore packages
        run: dotnet restore EmployeesTasksTracker.sln
        
      - name: Run unit tests
        run: dotnet test Tests\UnitTests\UnitTests.csproj \
          --configuration $BUILD_CONFIGURATION \
          --no-build \
          --verbosity normal
          
  integration-tests:

    runs-on: ubuntu-latest

    needs: build

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore packages
        run: dotnet restore EmployeesTasksTracker.sln
        
      - name: Run integration tests
        run: dotnet test Tests\IntegrationTests\IntegrationTests.csproj \
          --configuration $BUILD_CONFIGURATION \
          --no-build \
          --verbosity normal
