name: CI

on: 
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: List SDKs
        run: dotnet --list-sdks
        
      - name: Restore dependencies
        run: dotnet restore EmployeesTasksTracker.sln

      - name: Build
        run: dotnet build EmployeesTasksTracker.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test EmployeesTasksTracker.sln --configuration Release --no-build
